// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pin.LiveSports.Core.Data;

#nullable disable

namespace Pin.LiveSports.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pin.LiveSports.Core.Models.Champion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Champions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7cbee14c-da44-4160-b921-0097379b7cb5"),
                            Name = "Aatrox"
                        },
                        new
                        {
                            Id = new Guid("eb2e9ad7-c24d-442d-b98e-4b991d4b360d"),
                            Name = "Ahri"
                        },
                        new
                        {
                            Id = new Guid("593a4e5a-8dd3-45ad-90cd-7fc411dee77c"),
                            Name = "Akali"
                        },
                        new
                        {
                            Id = new Guid("90401b9f-4b2b-4b7e-a5bf-75403e174f7f"),
                            Name = "Alistar"
                        },
                        new
                        {
                            Id = new Guid("a1ff0caf-ddcd-4134-8e2d-342185047466"),
                            Name = "Amumu"
                        },
                        new
                        {
                            Id = new Guid("46db4fa1-6a48-45ce-955c-b6def3e09651"),
                            Name = "Anivia"
                        },
                        new
                        {
                            Id = new Guid("429fae04-b83a-4930-b975-65502dfc2c5a"),
                            Name = "Annie"
                        },
                        new
                        {
                            Id = new Guid("4b1cc565-9f3f-4634-bee5-b5632be42dcb"),
                            Name = "Aphelios"
                        },
                        new
                        {
                            Id = new Guid("b7e41fdf-76d0-4fcf-afd7-d3008a65fbfa"),
                            Name = "Ashe"
                        },
                        new
                        {
                            Id = new Guid("cc16844b-4746-46ab-aa4c-c0491a9cd4d5"),
                            Name = "Aurelion Sol"
                        },
                        new
                        {
                            Id = new Guid("c55083b7-9ffb-4123-91d8-6b8e8cd34b7d"),
                            Name = "Azir"
                        },
                        new
                        {
                            Id = new Guid("258e8a21-bff1-4092-9556-a7562ab5f5e9"),
                            Name = "Bard"
                        },
                        new
                        {
                            Id = new Guid("e95384b9-a572-4920-af48-f6e8dd9cdd5a"),
                            Name = "Blitzcrank"
                        },
                        new
                        {
                            Id = new Guid("90c2a07d-6843-457d-b173-0ed34b963f2f"),
                            Name = "Brand"
                        },
                        new
                        {
                            Id = new Guid("647ba38f-4556-46f7-8a81-19d358dcedca"),
                            Name = "Braum"
                        },
                        new
                        {
                            Id = new Guid("8933fc8d-3753-4fcc-817b-e8ee1960b934"),
                            Name = "Caitlyn"
                        },
                        new
                        {
                            Id = new Guid("6f381c31-af72-4941-ae02-8801e73c44d8"),
                            Name = "Camille"
                        },
                        new
                        {
                            Id = new Guid("32ac4a0f-7a7a-4323-9e64-765c20826cb6"),
                            Name = "Cassiopeia"
                        },
                        new
                        {
                            Id = new Guid("a0aed77d-02ae-4c1c-baa8-a083c5f17eb7"),
                            Name = "Cho gath"
                        },
                        new
                        {
                            Id = new Guid("b5e08a69-7745-4089-a871-e86cfc21bbef"),
                            Name = "Corki"
                        },
                        new
                        {
                            Id = new Guid("e17e1460-e901-4ba2-b4a7-e388c2cfbe5d"),
                            Name = "Darius"
                        },
                        new
                        {
                            Id = new Guid("eb4d5c8a-2701-4116-b6f7-82f4e1a2dc2d"),
                            Name = "Diana"
                        },
                        new
                        {
                            Id = new Guid("006f5784-e423-4865-842c-86f5fe843222"),
                            Name = "Draven"
                        },
                        new
                        {
                            Id = new Guid("6a1f3bf4-b784-45f6-a1b2-509c59d5b039"),
                            Name = "Dr Mundo"
                        },
                        new
                        {
                            Id = new Guid("fd25f55d-85e5-4de9-919a-f0282694c8c9"),
                            Name = "Ekko"
                        },
                        new
                        {
                            Id = new Guid("85d600c8-038b-41de-b8cc-077c07e5735d"),
                            Name = "Elise"
                        },
                        new
                        {
                            Id = new Guid("7c26a7dd-dcbe-4fdc-836f-046af9cec1bd"),
                            Name = "Evelynn"
                        },
                        new
                        {
                            Id = new Guid("203b1aee-a967-496a-b0df-2054126af6b0"),
                            Name = "Ezreal"
                        },
                        new
                        {
                            Id = new Guid("70ef3ad1-d403-4258-87f2-c669d78b2ba8"),
                            Name = "Fiddlesticks"
                        },
                        new
                        {
                            Id = new Guid("8eb5ed80-0c44-41c7-ace1-17b27b07ff47"),
                            Name = "Fiora"
                        },
                        new
                        {
                            Id = new Guid("f0ca12a6-d2a3-49af-ba60-1092c7ad7d68"),
                            Name = "Fizz"
                        },
                        new
                        {
                            Id = new Guid("6961aa71-4a52-4db3-84e5-326b6addc924"),
                            Name = "Galio"
                        },
                        new
                        {
                            Id = new Guid("f32a5f1a-283c-40ab-817f-04b547d75a3b"),
                            Name = "Gangplank"
                        },
                        new
                        {
                            Id = new Guid("2e63a3fe-2981-4e5f-860c-2f627176b4d3"),
                            Name = "Garen"
                        },
                        new
                        {
                            Id = new Guid("12abe70c-e79c-4564-8ce8-96641e874f80"),
                            Name = "Gnar"
                        },
                        new
                        {
                            Id = new Guid("46fcdc70-94bf-475d-a8f7-421ef11ef2e7"),
                            Name = "Gragas"
                        },
                        new
                        {
                            Id = new Guid("68475ad7-7d92-4d0f-886b-4b6065d3ce1a"),
                            Name = "Graves"
                        },
                        new
                        {
                            Id = new Guid("7a112947-7ecf-4f19-836f-918890a6326c"),
                            Name = "Hecarim"
                        },
                        new
                        {
                            Id = new Guid("cfcd7e49-33c7-47e6-9ff9-a842a2b9cddb"),
                            Name = "Heimerdinger"
                        },
                        new
                        {
                            Id = new Guid("14656281-7cbb-4bfb-bc48-76cbcaec258c"),
                            Name = "Illaoi"
                        },
                        new
                        {
                            Id = new Guid("12c61921-5507-48cf-b74a-8dc3c2289257"),
                            Name = "Irelia"
                        },
                        new
                        {
                            Id = new Guid("c6a2b938-c6a4-42f3-88dc-7c117a1eff92"),
                            Name = "Ivern"
                        },
                        new
                        {
                            Id = new Guid("b7ec3e94-6046-4067-8319-a24b2771fe1d"),
                            Name = "Janna"
                        },
                        new
                        {
                            Id = new Guid("37754b85-c6ef-4103-9381-f69782cbe400"),
                            Name = "Jarvan IV"
                        },
                        new
                        {
                            Id = new Guid("593a13de-891b-4f0b-9a09-b43c8c6be644"),
                            Name = "Jax"
                        },
                        new
                        {
                            Id = new Guid("3525f601-f20a-4c0f-94e8-b16edc0f3dfc"),
                            Name = "Jayce"
                        },
                        new
                        {
                            Id = new Guid("66560c01-1b2a-4c99-a7f3-7ba1b3caa22c"),
                            Name = "Jhin"
                        },
                        new
                        {
                            Id = new Guid("51c3e242-d433-4ef7-a1d3-9e6bb191ecb1"),
                            Name = "Jinx"
                        },
                        new
                        {
                            Id = new Guid("1fe79fd7-e8d7-4b31-8ef4-a632803655bb"),
                            Name = "Kaisa"
                        },
                        new
                        {
                            Id = new Guid("a41a3bcc-3e6d-412c-9b73-48c57974e480"),
                            Name = "Kalista"
                        },
                        new
                        {
                            Id = new Guid("3f0b2ba0-aca4-4fb7-bf6f-99948832ea97"),
                            Name = "Karma"
                        },
                        new
                        {
                            Id = new Guid("e6cf0389-1fa0-4169-a54f-9874b80e0eda"),
                            Name = "Karthus"
                        },
                        new
                        {
                            Id = new Guid("c5cf3bf7-5ebd-4f2d-adb2-aaf6a3137183"),
                            Name = "Kassadin"
                        },
                        new
                        {
                            Id = new Guid("5234c08e-5dac-49f1-a7fc-998018971ee0"),
                            Name = "Katarina"
                        },
                        new
                        {
                            Id = new Guid("ca297559-9a5b-4a59-a845-6b570433f696"),
                            Name = "Kayle"
                        },
                        new
                        {
                            Id = new Guid("1dfed61b-2de2-4892-833d-304126817eb5"),
                            Name = "Kayn"
                        },
                        new
                        {
                            Id = new Guid("5b0f672c-333c-4d74-a16f-fa991efbcdb0"),
                            Name = "Kennen"
                        },
                        new
                        {
                            Id = new Guid("7cc8268b-72b9-4d52-9f50-97db9d550769"),
                            Name = "Khazix"
                        },
                        new
                        {
                            Id = new Guid("1e6adb7c-47e6-4205-a3fb-6a74c69fdd59"),
                            Name = "Kindred"
                        },
                        new
                        {
                            Id = new Guid("9000e723-e7ae-4750-ad91-624b5147323a"),
                            Name = "Kled"
                        },
                        new
                        {
                            Id = new Guid("9fcec9fd-f46b-4c1c-8d36-06bcc950197f"),
                            Name = "Kog Maw"
                        },
                        new
                        {
                            Id = new Guid("12e9ae8b-9dc8-4fc6-a6d7-58f0c3fc4de2"),
                            Name = "Leblanc"
                        },
                        new
                        {
                            Id = new Guid("65dee88c-3614-4dda-ace0-de99b330c412"),
                            Name = "Lee Sin"
                        },
                        new
                        {
                            Id = new Guid("f0fcf713-75ac-4cec-a45b-d438c3acf490"),
                            Name = "Leona"
                        },
                        new
                        {
                            Id = new Guid("191b9cb2-ae6d-472c-a56d-adc0c2137432"),
                            Name = "Lillia"
                        },
                        new
                        {
                            Id = new Guid("da903bd1-ac49-4111-8f93-a31ac11014b4"),
                            Name = "Lissandra"
                        },
                        new
                        {
                            Id = new Guid("5b49a822-85fa-4148-a328-a6feb96f7794"),
                            Name = "Lucian"
                        },
                        new
                        {
                            Id = new Guid("5cb4a3d7-13d7-4ec6-b313-08ab023de9b9"),
                            Name = "Lulu"
                        },
                        new
                        {
                            Id = new Guid("8c590d2d-71cb-4405-8be2-2ab396382a6c"),
                            Name = "Lux"
                        },
                        new
                        {
                            Id = new Guid("4102221d-9bbe-4f1e-8708-a164c44562a4"),
                            Name = "Malphite"
                        },
                        new
                        {
                            Id = new Guid("f96efc56-771c-45a7-bd07-a49d645b7964"),
                            Name = "Malzahar"
                        },
                        new
                        {
                            Id = new Guid("da1280d8-bcf5-47c6-a4e2-30934d94c9ea"),
                            Name = "Maokai"
                        },
                        new
                        {
                            Id = new Guid("52f7d021-1391-456f-8f8a-2a0d9c41d301"),
                            Name = "Master Yi"
                        },
                        new
                        {
                            Id = new Guid("9df7d9da-fafe-4f97-bbdd-4682eac31dd9"),
                            Name = "Miss Fortune"
                        },
                        new
                        {
                            Id = new Guid("c60ba8b5-cf92-4e29-b296-33277452921d"),
                            Name = "Monkey King"
                        },
                        new
                        {
                            Id = new Guid("87855bd4-0121-4c33-8683-e7798f756c56"),
                            Name = "Mordekaiser"
                        },
                        new
                        {
                            Id = new Guid("b837f45b-f5c2-4a5e-8347-97a95cf0a1f1"),
                            Name = "Morgana"
                        },
                        new
                        {
                            Id = new Guid("3b95267c-8c1e-46b9-870f-62390c123c48"),
                            Name = "Nami"
                        },
                        new
                        {
                            Id = new Guid("7622ec5b-af04-491f-9fe5-53298fa0793d"),
                            Name = "Nasus"
                        },
                        new
                        {
                            Id = new Guid("3d71164e-a8a0-4741-b677-62930528df9b"),
                            Name = "Nautilus"
                        },
                        new
                        {
                            Id = new Guid("616162f8-daed-4ac2-b015-9002b080c64e"),
                            Name = "Neeko"
                        },
                        new
                        {
                            Id = new Guid("0245ce2b-e68f-4a60-9526-2152e40038cf"),
                            Name = "Nidalee"
                        },
                        new
                        {
                            Id = new Guid("460121c7-a869-4bb1-a555-32e12b4cb679"),
                            Name = "Nocturne"
                        },
                        new
                        {
                            Id = new Guid("4ec9b3ef-f4cb-486c-b54d-6449c160c53e"),
                            Name = "Nunu"
                        },
                        new
                        {
                            Id = new Guid("7621134e-033a-40a3-be46-f3136da770c4"),
                            Name = "Olaf"
                        },
                        new
                        {
                            Id = new Guid("67091be8-3307-4fe3-85d7-0fda410eb524"),
                            Name = "Orianna"
                        },
                        new
                        {
                            Id = new Guid("6c103c67-a63d-4d59-b99e-e16d239a7012"),
                            Name = "Ornn"
                        },
                        new
                        {
                            Id = new Guid("cd385246-5306-495e-adab-53def2621b2a"),
                            Name = "Pantheon"
                        },
                        new
                        {
                            Id = new Guid("d53b0db1-88be-462d-8257-3b8a9caa03a8"),
                            Name = "Poppy"
                        },
                        new
                        {
                            Id = new Guid("9ea5eafd-d0f8-4609-8063-d92569302537"),
                            Name = "Pyke"
                        },
                        new
                        {
                            Id = new Guid("650b5f4a-72fb-48fd-9935-6cfbe4cfb7e3"),
                            Name = "Qiyana"
                        },
                        new
                        {
                            Id = new Guid("72322092-cd7b-46bd-b7af-e6b17b13185d"),
                            Name = "Quinn"
                        },
                        new
                        {
                            Id = new Guid("2ec5b7a4-d619-42ea-8b6e-00432689dc51"),
                            Name = "Rakan"
                        },
                        new
                        {
                            Id = new Guid("28ae9c8c-cea2-4f83-a2d4-ef98202f80bc"),
                            Name = "Rammus"
                        },
                        new
                        {
                            Id = new Guid("696daffe-9fd7-41ea-8ec0-6ab68db989a9"),
                            Name = "RekSai"
                        },
                        new
                        {
                            Id = new Guid("71d6a923-716d-4342-af5a-4bc927c6a3c3"),
                            Name = "Renekton"
                        },
                        new
                        {
                            Id = new Guid("d502ab17-9080-4720-9b86-d8735089d8d2"),
                            Name = "Rengar"
                        },
                        new
                        {
                            Id = new Guid("ed2f91fa-d413-4c7a-9773-2f4589b488d4"),
                            Name = "Riven"
                        },
                        new
                        {
                            Id = new Guid("a4ebd866-5c64-43bf-a14b-71dabcb4f634"),
                            Name = "Rumble"
                        },
                        new
                        {
                            Id = new Guid("b9af01cf-1470-4c30-b996-1ad1737db252"),
                            Name = "Ryze"
                        },
                        new
                        {
                            Id = new Guid("f72d4e78-d3f6-4067-8eb4-720ced59f5f1"),
                            Name = "Samira"
                        },
                        new
                        {
                            Id = new Guid("c63f5d99-3512-4287-8982-94b4788b5884"),
                            Name = "Sejuani"
                        },
                        new
                        {
                            Id = new Guid("97f3544d-2af5-4eaa-bb4f-f616d4b0c236"),
                            Name = "Senna"
                        },
                        new
                        {
                            Id = new Guid("d3149aa1-503b-44dc-841b-179bdd1c629f"),
                            Name = "Seraphine"
                        },
                        new
                        {
                            Id = new Guid("fc4d740b-7595-4c07-a0ab-95e786105992"),
                            Name = "Sett"
                        },
                        new
                        {
                            Id = new Guid("12967cbc-b67f-440d-aadd-04069dac6059"),
                            Name = "Shaco"
                        },
                        new
                        {
                            Id = new Guid("11486d38-2b5e-43cc-ba53-25f8ef3c4ecd"),
                            Name = "Shen"
                        },
                        new
                        {
                            Id = new Guid("2bd19bf2-844c-4ad1-a502-6f350c6b1131"),
                            Name = "Shyvana"
                        },
                        new
                        {
                            Id = new Guid("df6046ca-f59d-4d45-8d18-8f02bcf0867b"),
                            Name = "Singed"
                        },
                        new
                        {
                            Id = new Guid("e621f670-4e96-4ede-a16c-a82bd9ec43ca"),
                            Name = "Sion"
                        },
                        new
                        {
                            Id = new Guid("7c0c0caa-c266-4870-b95c-de0403cf1678"),
                            Name = "Sivir"
                        },
                        new
                        {
                            Id = new Guid("b6ccedf7-5714-4933-ab26-b99010d48919"),
                            Name = "Skarner"
                        },
                        new
                        {
                            Id = new Guid("25025704-b7a5-4953-a5a6-c3b4a5378faa"),
                            Name = "Sona"
                        },
                        new
                        {
                            Id = new Guid("857b35d5-43f5-453c-9beb-77c03b4e15dc"),
                            Name = "Soraka"
                        },
                        new
                        {
                            Id = new Guid("9c712da0-eec2-4a67-8d0e-02488f26a191"),
                            Name = "Swain"
                        },
                        new
                        {
                            Id = new Guid("e68ba343-42bf-4b9f-b74f-44c31f79eb81"),
                            Name = "Sylas"
                        },
                        new
                        {
                            Id = new Guid("03bc9130-b1d8-4545-bc18-144ca15d2583"),
                            Name = "Syndra"
                        },
                        new
                        {
                            Id = new Guid("5f0928f1-9a83-4253-b7c5-334f3427f759"),
                            Name = "Tahm Kench"
                        },
                        new
                        {
                            Id = new Guid("463a937d-c1d2-4c29-bd19-b68735724f15"),
                            Name = "Taliyah"
                        },
                        new
                        {
                            Id = new Guid("1d346a0a-337d-46f3-853f-7c58ef91b7c9"),
                            Name = "Talon"
                        },
                        new
                        {
                            Id = new Guid("a2a4c821-dd5c-4b3a-b4ed-c4be5903bdae"),
                            Name = "Taric"
                        },
                        new
                        {
                            Id = new Guid("658d53a1-7657-48b9-8821-d42a97c135d2"),
                            Name = "Teemo"
                        },
                        new
                        {
                            Id = new Guid("0e1229c9-ac97-4845-b40e-91bff4bdb4ad"),
                            Name = "Thresh"
                        },
                        new
                        {
                            Id = new Guid("753d4e43-3c87-43f6-b558-1abfea161b6b"),
                            Name = "Tristana"
                        },
                        new
                        {
                            Id = new Guid("f0134760-eebb-4ba2-9d49-f9506ff90e80"),
                            Name = "Trundle"
                        },
                        new
                        {
                            Id = new Guid("af3a6744-c3de-47c9-a91c-6b0713b378e3"),
                            Name = "Tryndamere"
                        },
                        new
                        {
                            Id = new Guid("164baa8d-bd1c-4afa-8efd-db57548351f4"),
                            Name = "Twisted Fate"
                        },
                        new
                        {
                            Id = new Guid("cee0c5c6-249e-4b23-9e50-63eb3cc2661c"),
                            Name = "Twitch"
                        },
                        new
                        {
                            Id = new Guid("e562e40c-5fca-45ea-9645-137385743cff"),
                            Name = "Udyr"
                        },
                        new
                        {
                            Id = new Guid("b575d302-9d6c-4064-8e0a-c1cfe423d65a"),
                            Name = "Urgot"
                        },
                        new
                        {
                            Id = new Guid("e5e37e00-c074-46ed-b64f-bc6fbdb42da4"),
                            Name = "Varus"
                        },
                        new
                        {
                            Id = new Guid("79887249-eadb-46a9-b1b1-745ccf676198"),
                            Name = "Vayne"
                        },
                        new
                        {
                            Id = new Guid("3d52f607-3ef8-4f48-8a24-5f4aa66d087f"),
                            Name = "Veigar"
                        },
                        new
                        {
                            Id = new Guid("d3d71f49-b71c-4238-97fc-91bd0e7ec333"),
                            Name = "Velkoz"
                        },
                        new
                        {
                            Id = new Guid("ae3525ec-0d4d-4fab-b47e-201d8e3f2956"),
                            Name = "Vi"
                        },
                        new
                        {
                            Id = new Guid("9fa9c5ac-d70d-48e7-8b94-d5146116868f"),
                            Name = "Viktor"
                        },
                        new
                        {
                            Id = new Guid("c20c9190-a063-486e-a859-1ca5fb258c15"),
                            Name = "Vladimir"
                        },
                        new
                        {
                            Id = new Guid("9cbc4f2c-598d-4489-94ee-53491cbc6a39"),
                            Name = "Volibear"
                        },
                        new
                        {
                            Id = new Guid("943b11fa-4757-48ba-925d-699dccd25645"),
                            Name = "Warwick"
                        },
                        new
                        {
                            Id = new Guid("bd2a1d29-7746-4cd6-b19b-9376dfe1be3d"),
                            Name = "Xayah"
                        },
                        new
                        {
                            Id = new Guid("1b73078c-b31f-4d02-a461-2e98f688e5d5"),
                            Name = "Xerath"
                        },
                        new
                        {
                            Id = new Guid("57c717ff-6a83-4dd6-bfd5-b98950ed47e0"),
                            Name = "Xin Zhao"
                        },
                        new
                        {
                            Id = new Guid("3f073e85-a647-41fe-91ef-598d48317606"),
                            Name = "Yasuo"
                        },
                        new
                        {
                            Id = new Guid("6b38cb54-6f70-45ae-a83f-856c1dad94a2"),
                            Name = "Yone"
                        },
                        new
                        {
                            Id = new Guid("ce2706d4-1aa2-4912-921e-5f36fcf70ba2"),
                            Name = "Yorick"
                        },
                        new
                        {
                            Id = new Guid("ac530e99-3b6c-4ea1-88d9-6fcbb539d433"),
                            Name = "Yuumi"
                        },
                        new
                        {
                            Id = new Guid("003ba693-afc2-4b48-ba37-21469aeb6eb1"),
                            Name = "Zac"
                        },
                        new
                        {
                            Id = new Guid("284a2eef-95ef-49d0-a3b0-ac70776b4dae"),
                            Name = "Zed"
                        },
                        new
                        {
                            Id = new Guid("c7617c43-25d2-44d7-b62c-d24aba9672a3"),
                            Name = "Ziggs"
                        },
                        new
                        {
                            Id = new Guid("73d7bb52-78ad-47a8-8f2f-73caf1e59aa8"),
                            Name = "Zilean"
                        },
                        new
                        {
                            Id = new Guid("242235e1-6b91-49ce-a674-3ae5493c9c2f"),
                            Name = "Zoe"
                        },
                        new
                        {
                            Id = new Guid("0c067046-9fcf-4305-acb8-a22a3ba127c2"),
                            Name = "Zyra"
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlueTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BlueTeamWins")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MatchTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RedTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RedTeamWins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlueTeamId");

                    b.HasIndex("MatchTypeId");

                    b.HasIndex("RedTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Models.MatchType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredWins")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MatchTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("647be9e1-73de-4780-aad7-fdd124f688e3"),
                            Name = "Best of 1",
                            RequiredWins = 1,
                            ShortName = "Bo1"
                        },
                        new
                        {
                            Id = new Guid("01969dca-7362-42c6-87cd-44d9d97b9e7c"),
                            Name = "Best of 3",
                            RequiredWins = 2,
                            ShortName = "Bo3"
                        },
                        new
                        {
                            Id = new Guid("30ff682c-c3c1-4bfe-ae02-73f385ce3825"),
                            Name = "Best of 5",
                            RequiredWins = 3,
                            ShortName = "Bo5"
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoleId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a645ea51-2c88-4f4f-baf8-907550d3ccdd"),
                            ImageUrl = "players/g2/caps.png",
                            Name = "RASMUS BORREGAARD WINTHER",
                            PlayerName = "Caps",
                            RoleId = new Guid("b580ae0b-24af-4c47-ab4f-01bd4063b43b"),
                            TeamId = new Guid("c8a8b7f1-33f5-4f96-b1d5-59286c0eb3a2")
                        },
                        new
                        {
                            Id = new Guid("34e4be6d-d7ab-4caa-8316-f0814f70ff97"),
                            ImageUrl = "players/g2/brokenblade.png",
                            Name = "SERGEN ÇELIK",
                            PlayerName = "BrokenBlade",
                            RoleId = new Guid("1fe1ed1b-5b07-4421-b6db-ceda19c1530d"),
                            TeamId = new Guid("c8a8b7f1-33f5-4f96-b1d5-59286c0eb3a2")
                        },
                        new
                        {
                            Id = new Guid("57259fc4-da63-4f1b-996f-b4d511ff571f"),
                            ImageUrl = "players/g2/hanssama.png",
                            Name = "STEVEN LIV",
                            PlayerName = "Hans Sama",
                            RoleId = new Guid("bc38e99b-85b8-4c62-8df0-fea42d734984"),
                            TeamId = new Guid("c8a8b7f1-33f5-4f96-b1d5-59286c0eb3a2")
                        },
                        new
                        {
                            Id = new Guid("1f4d1bea-35d8-4fbf-8345-529b94a3b0a7"),
                            ImageUrl = "players/g2/skewmond.png",
                            Name = "RUDY SEMAAN",
                            PlayerName = "SkewMond",
                            RoleId = new Guid("790e51b8-259b-4d36-b5f1-131c41128234"),
                            TeamId = new Guid("c8a8b7f1-33f5-4f96-b1d5-59286c0eb3a2")
                        },
                        new
                        {
                            Id = new Guid("2baf0fcc-fce2-40a3-9cc1-56b77bb4a733"),
                            ImageUrl = "players/g2/labrov.png",
                            Name = "LABROS PAPOUTSAKIS",
                            PlayerName = "Labrov",
                            RoleId = new Guid("a9ba8fa3-84ff-4333-94ad-cf0f7a1dac86"),
                            TeamId = new Guid("c8a8b7f1-33f5-4f96-b1d5-59286c0eb3a2")
                        },
                        new
                        {
                            Id = new Guid("3b2c5685-3f76-482a-92e8-a72fab088fae"),
                            ImageUrl = "players/kc/vladi.png",
                            Name = "VLADIMIROS KOURTIDIS",
                            PlayerName = "Vladi",
                            RoleId = new Guid("b580ae0b-24af-4c47-ab4f-01bd4063b43b"),
                            TeamId = new Guid("d5206d52-d495-4b2a-af8d-ea3eb5bf2e4d")
                        },
                        new
                        {
                            Id = new Guid("90d43f7f-99c0-4f95-b657-079cc4a89288"),
                            ImageUrl = "players/kc/canna.png",
                            Name = "CHANGDONG KIM",
                            PlayerName = "Canna",
                            RoleId = new Guid("1fe1ed1b-5b07-4421-b6db-ceda19c1530d"),
                            TeamId = new Guid("d5206d52-d495-4b2a-af8d-ea3eb5bf2e4d")
                        },
                        new
                        {
                            Id = new Guid("ab169580-fd4a-4ed6-ba86-f1faf0fc7f1b"),
                            ImageUrl = "players/kc/caliste.png",
                            Name = "CALISTE HENRY-HENNEBERT",
                            PlayerName = "Caliste",
                            RoleId = new Guid("bc38e99b-85b8-4c62-8df0-fea42d734984"),
                            TeamId = new Guid("d5206d52-d495-4b2a-af8d-ea3eb5bf2e4d")
                        },
                        new
                        {
                            Id = new Guid("c71976c1-46ba-4831-a08f-888231875ce5"),
                            ImageUrl = "players/kc/yike.png",
                            Name = "MARTIN SUNDELIN",
                            PlayerName = "Yike",
                            RoleId = new Guid("790e51b8-259b-4d36-b5f1-131c41128234"),
                            TeamId = new Guid("d5206d52-d495-4b2a-af8d-ea3eb5bf2e4d")
                        },
                        new
                        {
                            Id = new Guid("40204dcb-8305-47a2-ad7c-98e69c8c73ff"),
                            ImageUrl = "players/kc/targamas.png",
                            Name = "RAPHAEL CRABBÉ",
                            PlayerName = "Targamas",
                            RoleId = new Guid("a9ba8fa3-84ff-4333-94ad-cf0f7a1dac86"),
                            TeamId = new Guid("d5206d52-d495-4b2a-af8d-ea3eb5bf2e4d")
                        },
                        new
                        {
                            Id = new Guid("c0c04ac0-2b1a-4dd6-8976-188cd0550481"),
                            ImageUrl = "players/bds/nuc.png",
                            Name = "ILIAS BIZRIKEN",
                            PlayerName = "nuc",
                            RoleId = new Guid("b580ae0b-24af-4c47-ab4f-01bd4063b43b"),
                            TeamId = new Guid("89c913b2-be0d-48eb-924c-7ff4831a5ebb")
                        },
                        new
                        {
                            Id = new Guid("3cb2311b-24d0-4cfd-be95-5d66fe700273"),
                            ImageUrl = "players/bds/irrelevant.png",
                            Name = "JOEL MIRO SCHAROLL",
                            PlayerName = "Irrelevant",
                            RoleId = new Guid("1fe1ed1b-5b07-4421-b6db-ceda19c1530d"),
                            TeamId = new Guid("89c913b2-be0d-48eb-924c-7ff4831a5ebb")
                        },
                        new
                        {
                            Id = new Guid("ac9c6a44-4990-446a-be7b-fc34e82a01fc"),
                            ImageUrl = "players/bds/ice.png",
                            Name = "SANG-HOON YOON",
                            PlayerName = "Ice",
                            RoleId = new Guid("bc38e99b-85b8-4c62-8df0-fea42d734984"),
                            TeamId = new Guid("89c913b2-be0d-48eb-924c-7ff4831a5ebb")
                        },
                        new
                        {
                            Id = new Guid("ef328d8d-fabd-426f-ae86-fec72a65daef"),
                            ImageUrl = "players/bds/113.png",
                            Name = "DOĞUKAN BALCI",
                            PlayerName = "113",
                            RoleId = new Guid("790e51b8-259b-4d36-b5f1-131c41128234"),
                            TeamId = new Guid("89c913b2-be0d-48eb-924c-7ff4831a5ebb")
                        },
                        new
                        {
                            Id = new Guid("08781b03-07fa-4048-94ec-b7e98ff7cac1"),
                            ImageUrl = "players/bds/parus.png",
                            Name = "POLAT FURKAN ÇIÇEK",
                            PlayerName = "Parus",
                            RoleId = new Guid("a9ba8fa3-84ff-4333-94ad-cf0f7a1dac86"),
                            TeamId = new Guid("89c913b2-be0d-48eb-924c-7ff4831a5ebb")
                        },
                        new
                        {
                            Id = new Guid("9cfb9ca2-14df-4c2b-ab8a-3e0d1672a9ac"),
                            ImageUrl = "players/fnc/humanoid.png",
                            Name = "MAREK BRÁZDA",
                            PlayerName = "Humanoid",
                            RoleId = new Guid("b580ae0b-24af-4c47-ab4f-01bd4063b43b"),
                            TeamId = new Guid("51cd5842-b00f-4b87-b985-0ce797e61ce8")
                        },
                        new
                        {
                            Id = new Guid("82a8d52a-c8cc-4de5-b654-18f6cebdc37c"),
                            ImageUrl = "players/fnc/oscarinin.png",
                            Name = "OSCAR MUÑOZ JIMÉNEZ",
                            PlayerName = "Oscarinin",
                            RoleId = new Guid("1fe1ed1b-5b07-4421-b6db-ceda19c1530d"),
                            TeamId = new Guid("51cd5842-b00f-4b87-b985-0ce797e61ce8")
                        },
                        new
                        {
                            Id = new Guid("215c0f00-14a7-415a-97ad-936fa0d62821"),
                            ImageUrl = "players/fnc/upset.png",
                            Name = "ELIAS LIPP",
                            PlayerName = "Upset",
                            RoleId = new Guid("bc38e99b-85b8-4c62-8df0-fea42d734984"),
                            TeamId = new Guid("51cd5842-b00f-4b87-b985-0ce797e61ce8")
                        },
                        new
                        {
                            Id = new Guid("8bdd1dc5-7cf5-4516-a3f8-abe744cda839"),
                            ImageUrl = "players/fnc/razork.png",
                            Name = "IVÁN MARTÍN",
                            PlayerName = "Razork",
                            RoleId = new Guid("790e51b8-259b-4d36-b5f1-131c41128234"),
                            TeamId = new Guid("51cd5842-b00f-4b87-b985-0ce797e61ce8")
                        },
                        new
                        {
                            Id = new Guid("a386531a-3909-4384-a11f-6ff1f9491b55"),
                            ImageUrl = "players/fnc/mikyx.png",
                            Name = "MIHAEL MEHLE",
                            PlayerName = "Mikyx",
                            RoleId = new Guid("a9ba8fa3-84ff-4333-94ad-cf0f7a1dac86"),
                            TeamId = new Guid("51cd5842-b00f-4b87-b985-0ce797e61ce8")
                        },
                        new
                        {
                            Id = new Guid("671edc91-4c8e-428d-9a6b-29f397a09d50"),
                            ImageUrl = "players/sk/rkr.png",
                            Name = "STEVEN CHEN",
                            PlayerName = "RKR",
                            RoleId = new Guid("b580ae0b-24af-4c47-ab4f-01bd4063b43b"),
                            TeamId = new Guid("987408c0-6ed1-4e2d-a4f1-bb109d33d32a")
                        },
                        new
                        {
                            Id = new Guid("bacf759f-c097-44c6-85fa-f0b2e54ac5f6"),
                            ImageUrl = "players/sk/jnx.png",
                            Name = "JANIK BARTELS",
                            PlayerName = "JNX",
                            RoleId = new Guid("1fe1ed1b-5b07-4421-b6db-ceda19c1530d"),
                            TeamId = new Guid("987408c0-6ed1-4e2d-a4f1-bb109d33d32a")
                        },
                        new
                        {
                            Id = new Guid("ad04396f-d9f5-4946-aeb6-33a199344eb4"),
                            ImageUrl = "players/sk/keduii.png",
                            Name = "TIM WILLERS",
                            PlayerName = "Keduii",
                            RoleId = new Guid("bc38e99b-85b8-4c62-8df0-fea42d734984"),
                            TeamId = new Guid("987408c0-6ed1-4e2d-a4f1-bb109d33d32a")
                        },
                        new
                        {
                            Id = new Guid("55289d69-db2c-4e79-baed-2e21de163e7a"),
                            ImageUrl = "players/sk/boukada.png",
                            Name = "LAHLOU MEHDI",
                            PlayerName = "Boukada",
                            RoleId = new Guid("790e51b8-259b-4d36-b5f1-131c41128234"),
                            TeamId = new Guid("987408c0-6ed1-4e2d-a4f1-bb109d33d32a")
                        },
                        new
                        {
                            Id = new Guid("f6b64cc1-cf70-4270-86b9-012675f92c4f"),
                            ImageUrl = "players/sk/loopy.png",
                            Name = "DONGHYEON KIM",
                            PlayerName = "Loopy",
                            RoleId = new Guid("a9ba8fa3-84ff-4333-94ad-cf0f7a1dac86"),
                            TeamId = new Guid("987408c0-6ed1-4e2d-a4f1-bb109d33d32a")
                        },
                        new
                        {
                            Id = new Guid("9e244023-4dc1-46a6-b605-916638ef321f"),
                            ImageUrl = "players/th/kamiloo.png",
                            Name = "HAUDEGOND KAMIL",
                            PlayerName = "Kamiloo",
                            RoleId = new Guid("b580ae0b-24af-4c47-ab4f-01bd4063b43b"),
                            TeamId = new Guid("2dc1a206-84cf-4e83-b732-b89a052a41f6")
                        },
                        new
                        {
                            Id = new Guid("e0f41f94-21a4-4dd6-a76a-355d4c5a2f50"),
                            ImageUrl = "players/th/carlsen.png",
                            Name = "CARL ULSTED CARLSEN",
                            PlayerName = "Carlsen",
                            RoleId = new Guid("1fe1ed1b-5b07-4421-b6db-ceda19c1530d"),
                            TeamId = new Guid("2dc1a206-84cf-4e83-b732-b89a052a41f6")
                        },
                        new
                        {
                            Id = new Guid("b09e9b3b-d7de-400f-937d-1f7e13cd446e"),
                            ImageUrl = "players/th/flakked.png",
                            Name = "VICTOR LIROLA",
                            PlayerName = "Flakked",
                            RoleId = new Guid("bc38e99b-85b8-4c62-8df0-fea42d734984"),
                            TeamId = new Guid("2dc1a206-84cf-4e83-b732-b89a052a41f6")
                        },
                        new
                        {
                            Id = new Guid("63ab2d43-3714-488b-a092-4519cfbd35c8"),
                            ImageUrl = "players/th/sheo.png",
                            Name = "THÉO BORILE",
                            PlayerName = "Sheo",
                            RoleId = new Guid("790e51b8-259b-4d36-b5f1-131c41128234"),
                            TeamId = new Guid("2dc1a206-84cf-4e83-b732-b89a052a41f6")
                        },
                        new
                        {
                            Id = new Guid("90d9353b-69cd-4e50-b885-68b0f0021294"),
                            ImageUrl = "players/th/stend.png",
                            Name = "PAUL LARDIN",
                            PlayerName = "Stend",
                            RoleId = new Guid("a9ba8fa3-84ff-4333-94ad-cf0f7a1dac86"),
                            TeamId = new Guid("2dc1a206-84cf-4e83-b732-b89a052a41f6")
                        },
                        new
                        {
                            Id = new Guid("52dfc1a6-7fa2-4071-8e4f-4634b8222a6d"),
                            ImageUrl = "players/vit/czajek.png",
                            Name = "MATEUSZ CZAJKA",
                            PlayerName = "Czajek",
                            RoleId = new Guid("b580ae0b-24af-4c47-ab4f-01bd4063b43b"),
                            TeamId = new Guid("efea880f-4c15-43e5-b854-e536456e2594")
                        },
                        new
                        {
                            Id = new Guid("f0d4d9a7-685f-4de4-be51-61ef7c0567d0"),
                            ImageUrl = "players/vit/naaknako.png",
                            Name = "KAAN OKAN",
                            PlayerName = "Naak Nako",
                            RoleId = new Guid("1fe1ed1b-5b07-4421-b6db-ceda19c1530d"),
                            TeamId = new Guid("efea880f-4c15-43e5-b854-e536456e2594")
                        },
                        new
                        {
                            Id = new Guid("57240304-b77e-43ce-a50b-974106da95d1"),
                            ImageUrl = "players/vit/carzzy.png",
                            Name = "MATYÁŠ ORSÁG",
                            PlayerName = "Carzzy",
                            RoleId = new Guid("bc38e99b-85b8-4c62-8df0-fea42d734984"),
                            TeamId = new Guid("efea880f-4c15-43e5-b854-e536456e2594")
                        },
                        new
                        {
                            Id = new Guid("691df01e-bb62-4710-89e3-e2bb9958e8e7"),
                            ImageUrl = "players/vit/lyncas.png",
                            Name = "LINAS NAUNČIKAS",
                            PlayerName = "Lyncas",
                            RoleId = new Guid("790e51b8-259b-4d36-b5f1-131c41128234"),
                            TeamId = new Guid("efea880f-4c15-43e5-b854-e536456e2594")
                        },
                        new
                        {
                            Id = new Guid("67631fa2-39ad-4009-88ba-9dfcae1b031d"),
                            ImageUrl = "players/vit/nisqy.png",
                            Name = "YASIN DINCER",
                            PlayerName = "Nisqy",
                            RoleId = new Guid("a9ba8fa3-84ff-4333-94ad-cf0f7a1dac86"),
                            TeamId = new Guid("efea880f-4c15-43e5-b854-e536456e2594")
                        },
                        new
                        {
                            Id = new Guid("3afcbb53-f147-44fc-a1f7-bf51a614ced9"),
                            ImageUrl = "players/rge/larssen.png",
                            Name = "EMIL LARSSON",
                            PlayerName = "Larssen",
                            RoleId = new Guid("b580ae0b-24af-4c47-ab4f-01bd4063b43b"),
                            TeamId = new Guid("91c02af7-180e-49c8-a277-33c0fcf38be3")
                        },
                        new
                        {
                            Id = new Guid("3c6f9746-7c4a-4524-97ce-6f49b5171016"),
                            ImageUrl = "players/rge/adam.png",
                            Name = "ADAM MAANANE",
                            PlayerName = "Adam",
                            RoleId = new Guid("1fe1ed1b-5b07-4421-b6db-ceda19c1530d"),
                            TeamId = new Guid("91c02af7-180e-49c8-a277-33c0fcf38be3")
                        },
                        new
                        {
                            Id = new Guid("59847add-41ff-45c9-b3b4-42cedf23ff04"),
                            ImageUrl = "players/rge/patrik.png",
                            Name = "PATRIK JIRU",
                            PlayerName = "Patrik",
                            RoleId = new Guid("bc38e99b-85b8-4c62-8df0-fea42d734984"),
                            TeamId = new Guid("91c02af7-180e-49c8-a277-33c0fcf38be3")
                        },
                        new
                        {
                            Id = new Guid("5c7323b8-250a-483c-89a0-40618ce8377a"),
                            ImageUrl = "players/rge/malrang.png",
                            Name = "GEUN-SEONG KIM",
                            PlayerName = "Malrang",
                            RoleId = new Guid("790e51b8-259b-4d36-b5f1-131c41128234"),
                            TeamId = new Guid("91c02af7-180e-49c8-a277-33c0fcf38be3")
                        },
                        new
                        {
                            Id = new Guid("9b7f753a-26b8-4869-9292-19ca0962e36c"),
                            ImageUrl = "players/rge/execute.png",
                            Name = "JEONGHOON LEE",
                            PlayerName = "Execute",
                            RoleId = new Guid("a9ba8fa3-84ff-4333-94ad-cf0f7a1dac86"),
                            TeamId = new Guid("91c02af7-180e-49c8-a277-33c0fcf38be3")
                        },
                        new
                        {
                            Id = new Guid("843dcc7f-547c-4ed5-b402-cac81927fcc6"),
                            ImageUrl = "players/gx/jackies.png",
                            Name = "ADAM JEŘÁBEK",
                            PlayerName = "Jackies",
                            RoleId = new Guid("b580ae0b-24af-4c47-ab4f-01bd4063b43b"),
                            TeamId = new Guid("93cb0b9b-b929-48ef-bbfb-2cf6d66a6de0")
                        },
                        new
                        {
                            Id = new Guid("f021a7a6-f4d1-4e9b-9d2e-356b55b4c9db"),
                            ImageUrl = "players/gx/lot.png",
                            Name = "EREN YILDIZ",
                            PlayerName = "Lot",
                            RoleId = new Guid("1fe1ed1b-5b07-4421-b6db-ceda19c1530d"),
                            TeamId = new Guid("93cb0b9b-b929-48ef-bbfb-2cf6d66a6de0")
                        },
                        new
                        {
                            Id = new Guid("cc843fc8-d5e0-4e24-9b9b-2d4a7765a8af"),
                            ImageUrl = "players/gx/noah.png",
                            Name = "HYUNTAEK O",
                            PlayerName = "Noah",
                            RoleId = new Guid("bc38e99b-85b8-4c62-8df0-fea42d734984"),
                            TeamId = new Guid("93cb0b9b-b929-48ef-bbfb-2cf6d66a6de0")
                        },
                        new
                        {
                            Id = new Guid("40a79e5e-945e-4400-921f-648472503a0e"),
                            ImageUrl = "players/gx/isma.png",
                            Name = "ISMAÏL BOUALEM",
                            PlayerName = "ISMA",
                            RoleId = new Guid("790e51b8-259b-4d36-b5f1-131c41128234"),
                            TeamId = new Guid("93cb0b9b-b929-48ef-bbfb-2cf6d66a6de0")
                        },
                        new
                        {
                            Id = new Guid("4604f22e-c682-44f9-8511-ad6082504e0d"),
                            ImageUrl = "players/gx/jun.png",
                            Name = "SEJUN YOON",
                            PlayerName = "Jun",
                            RoleId = new Guid("a9ba8fa3-84ff-4333-94ad-cf0f7a1dac86"),
                            TeamId = new Guid("93cb0b9b-b929-48ef-bbfb-2cf6d66a6de0")
                        },
                        new
                        {
                            Id = new Guid("acfaf5ce-7b84-46f9-b2cf-039e40a05a69"),
                            ImageUrl = "players/mkoi/jojopyun.png",
                            Name = "JOSEPH JOON PYUN",
                            PlayerName = "Jojopyun",
                            RoleId = new Guid("b580ae0b-24af-4c47-ab4f-01bd4063b43b"),
                            TeamId = new Guid("1aa42b46-ac0b-439b-b1f6-1bcddb4fcc85")
                        },
                        new
                        {
                            Id = new Guid("b722a870-cc72-406e-a56c-ce6438ef8ebd"),
                            ImageUrl = "players/mkoi/myrwn.png",
                            Name = "ÁLEX VILLAREJO PASTOR",
                            PlayerName = "Myrwn",
                            RoleId = new Guid("1fe1ed1b-5b07-4421-b6db-ceda19c1530d"),
                            TeamId = new Guid("1aa42b46-ac0b-439b-b1f6-1bcddb4fcc85")
                        },
                        new
                        {
                            Id = new Guid("e056d564-dc49-46b6-9440-744a755c796e"),
                            ImageUrl = "players/mkoi/supa.png",
                            Name = "DAVID MARTÍNEZ GARCÍA",
                            PlayerName = "Supa",
                            RoleId = new Guid("bc38e99b-85b8-4c62-8df0-fea42d734984"),
                            TeamId = new Guid("1aa42b46-ac0b-439b-b1f6-1bcddb4fcc85")
                        },
                        new
                        {
                            Id = new Guid("f90821dc-8fed-4cc3-85ab-d1751de2bf79"),
                            ImageUrl = "players/mkoi/elyoya.png",
                            Name = "JAVIER PRADES",
                            PlayerName = "Elyoya",
                            RoleId = new Guid("790e51b8-259b-4d36-b5f1-131c41128234"),
                            TeamId = new Guid("1aa42b46-ac0b-439b-b1f6-1bcddb4fcc85")
                        },
                        new
                        {
                            Id = new Guid("70efc730-07f0-4b35-b9e3-8219c5b04820"),
                            ImageUrl = "players/mkoi/alvaro.png",
                            Name = "ALVARO FERNÁNDEZ DEL AMO",
                            PlayerName = "Alvaro",
                            RoleId = new Guid("a9ba8fa3-84ff-4333-94ad-cf0f7a1dac86"),
                            TeamId = new Guid("1aa42b46-ac0b-439b-b1f6-1bcddb4fcc85")
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("790e51b8-259b-4d36-b5f1-131c41128234"),
                            ImageUrl = "jungle.svg",
                            Name = "Jungle",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("1fe1ed1b-5b07-4421-b6db-ceda19c1530d"),
                            ImageUrl = "top.svg",
                            Name = "Top",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("b580ae0b-24af-4c47-ab4f-01bd4063b43b"),
                            ImageUrl = "mid.svg",
                            Name = "Mid",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("bc38e99b-85b8-4c62-8df0-fea42d734984"),
                            ImageUrl = "carry.svg",
                            Name = "AD Carry",
                            Order = 4
                        },
                        new
                        {
                            Id = new Guid("a9ba8fa3-84ff-4333-94ad-cf0f7a1dac86"),
                            ImageUrl = "support.svg",
                            Name = "Support",
                            Order = 5
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmallImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8a8b7f1-33f5-4f96-b1d5-59286c0eb3a2"),
                            ImageUrl = "logo/G2.png",
                            Losses = 0,
                            Name = "G2 Esports",
                            ShortName = "G2",
                            SmallImageUrl = "mini_logo/G2.png",
                            Wins = 0
                        },
                        new
                        {
                            Id = new Guid("51cd5842-b00f-4b87-b985-0ce797e61ce8"),
                            ImageUrl = "logo/FNC.png",
                            Losses = 0,
                            Name = "Fnatic",
                            ShortName = "FNC",
                            SmallImageUrl = "mini_logo/FNC.png",
                            Wins = 0
                        },
                        new
                        {
                            Id = new Guid("d5206d52-d495-4b2a-af8d-ea3eb5bf2e4d"),
                            ImageUrl = "logo/KC.png",
                            Losses = 0,
                            Name = "Karmine Corp",
                            ShortName = "KC",
                            SmallImageUrl = "mini_logo/KC.png",
                            Wins = 0
                        },
                        new
                        {
                            Id = new Guid("89c913b2-be0d-48eb-924c-7ff4831a5ebb"),
                            ImageUrl = "logo/BDS.png",
                            Losses = 0,
                            Name = "Team BDS",
                            ShortName = "BDS",
                            SmallImageUrl = "mini_logo/BDS.png",
                            Wins = 0
                        },
                        new
                        {
                            Id = new Guid("987408c0-6ed1-4e2d-a4f1-bb109d33d32a"),
                            ImageUrl = "logo/SK.png",
                            Losses = 0,
                            Name = "SK Gaming",
                            ShortName = "SK",
                            SmallImageUrl = "mini_logo/SK.png",
                            Wins = 0
                        },
                        new
                        {
                            Id = new Guid("2dc1a206-84cf-4e83-b732-b89a052a41f6"),
                            ImageUrl = "logo/TH.png",
                            Losses = 0,
                            Name = "Team Heretics",
                            ShortName = "TH",
                            SmallImageUrl = "mini_logo/TH.png",
                            Wins = 0
                        },
                        new
                        {
                            Id = new Guid("efea880f-4c15-43e5-b854-e536456e2594"),
                            ImageUrl = "logo/VIT.png",
                            Losses = 0,
                            Name = "Team Vitality",
                            ShortName = "VIT",
                            SmallImageUrl = "mini_logo/VIT.png",
                            Wins = 0
                        },
                        new
                        {
                            Id = new Guid("91c02af7-180e-49c8-a277-33c0fcf38be3"),
                            ImageUrl = "logo/RGE.png",
                            Losses = 0,
                            Name = "Rogue",
                            ShortName = "RGE",
                            SmallImageUrl = "mini_logo/RGE.png",
                            Wins = 0
                        },
                        new
                        {
                            Id = new Guid("93cb0b9b-b929-48ef-bbfb-2cf6d66a6de0"),
                            ImageUrl = "logo/GX.png",
                            Losses = 0,
                            Name = "GIANTX",
                            ShortName = "GX",
                            SmallImageUrl = "mini_logo/GX.png",
                            Wins = 0
                        },
                        new
                        {
                            Id = new Guid("1aa42b46-ac0b-439b-b1f6-1bcddb4fcc85"),
                            ImageUrl = "logo/MKOI.png",
                            Losses = 0,
                            Name = "Movistar KOI",
                            ShortName = "MKOI",
                            SmallImageUrl = "mini_logo/MKOI.png",
                            Wins = 0
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Models.Match", b =>
                {
                    b.HasOne("Pin.LiveSports.Core.Models.Team", "BlueTeam")
                        .WithMany()
                        .HasForeignKey("BlueTeamId");

                    b.HasOne("Pin.LiveSports.Core.Models.MatchType", "MatchType")
                        .WithMany()
                        .HasForeignKey("MatchTypeId");

                    b.HasOne("Pin.LiveSports.Core.Models.Team", "RedTeam")
                        .WithMany()
                        .HasForeignKey("RedTeamId");

                    b.Navigation("BlueTeam");

                    b.Navigation("MatchType");

                    b.Navigation("RedTeam");
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Models.Player", b =>
                {
                    b.HasOne("Pin.LiveSports.Core.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pin.LiveSports.Core.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.Navigation("Role");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
